IF(UNIX)

  IF(BFL_INCLUDE_DIR AND BFL_LIBRARIES)
    # in cache already
    SET(BFL_FIND_QUIETLY TRUE)
  ENDIF(BFL_INCLUDE_DIR AND BFL_LIBRARIES)

  MESSAGE(STATUS "Searching for BFL ...")

  FIND_PATH(BFL_INCLUDE_DIR
    NAMES bfl  
    PATHS
    /usr/local
    /usr
    PATH_SUFFIXES include/bfl include
  )
  IF (BFL_INCLUDE_DIR)
    MESSAGE(STATUS "Found BFL headers in: ${BFL_INCLUDE_DIR}")
  ENDIF (BFL_INCLUDE_DIR)

  FIND_LIBRARY(OROCOS_BFL_LIBRARIES 
    NAMES orocos-bfl    
    PATHS
    /usr/local
    /usr
    PATH_SUFFIXES lib
  )

  SET(BFL_LIBRARIES ${OROCOS_BFL_LIBRARIES})

ENDIF(UNIX)